[versions]
antlr = "4.13.2"
apacheCommonsLang = "3.19.0"
apacheCommonsText = "1.14.0"
asciiDoctorGradle = "4.0.5"
asm = "9.9"
bsp4j = "2.1.1"
directories = "26"
eclipseCollections = "13.0.0"
equalsVerifier = "4.2"
gradleBsp = "0.0.0-110-fa4ab1a-SNAPSHOT"
gradleBuildInfo = "0.3.1"
gradleNode = "7.1.0"
gradleVersions = "0.52.0"
gradleGitVersioning = "6.4.4"
gson = "2.13.2"
hamcrest = "3.0"
jacoco = "0.8.8"
jansi = "2.4.2"
jgrapht = "1.5.2"
jqwik = "1.9.3"
junit = "6.0.1"
junitPlatform = "6.0.1"
junixSocket = "2.10.1"
logback = "1.5.20"
lsp4j = "0.24.0"
picocli = "4.7.7"
prettier4j = "0.3.2"
protobuf = "4.33.0"
protobufGradle = "0.9.5"
pyroscopeAgent = "2.1.2"
reactorCore = "3.7.12"
slf4j = "2.0.17"
spotless = "8.0.0"
spotifyHamcrest = "1.3.2"
toStringVerifier = "1.4.8"
yvette = "0.1.0"

[libraries]
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlrRuntime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
apacheCommonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsLang" }
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsText" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asmCommons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asmUtil = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
bsp4j = { module = "ch.epfl.scala:bsp4j", version.ref = "bsp4j" }
directories = { module = "dev.dirs:directories", version.ref = "directories" }
eclipseCollections = { module = "org.eclipse.collections:eclipse-collections", version.ref = "eclipseCollections" }
eclipseCollectionsApi = { module = "org.eclipse.collections:eclipse-collections-api", version.ref = "eclipseCollections" }
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
gitVersioningPlugin = { module = "me.qoomon:gradle-git-versioning-plugin", version.ref = "gradleGitVersioning" }
gradleBspPlugin = { module = "com.opencastsoftware.gradle:gradle-bsp-plugin", version.ref = "gradleBsp" }
gradleVersionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradleVersions" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
hamcrestFuture = { module = "com.spotify:hamcrest-future", version.ref = "spotifyHamcrest" }
hamcrestOptional = { module = "com.spotify:hamcrest-optional", version.ref = "spotifyHamcrest" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jgrapht = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
jgraphtIo = { module = "org.jgrapht:jgrapht-io", version.ref = "jgrapht" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
julToSlf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
junixSocket = { module = "com.kohlschutter.junixsocket:junixsocket-core", version.ref = "junixSocket" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocliCodegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
prettier4j = { module = "com.opencastsoftware:prettier4j", version.ref = "prettier4j" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobufPlugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobufGradle" }
pyroscopeAgent = { module = "io.pyroscope:agent", version.ref = "pyroscopeAgent" }
reactorCore = { module = "io.projectreactor:reactor-core", version.ref = "reactorCore" }
reactorTest = { module = "io.projectreactor:reactor-test", version.ref = "reactorCore" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
spotlessGradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
toStringVerifier = { module = "com.jparams:to-string-verifier", version.ref = "toStringVerifier" }
yvette = { module = "com.opencastsoftware:yvette", version.ref = "yvette" }

[bundles]
eclipseCollections = ["eclipseCollectionsApi", "eclipseCollections"]
slf4j = ["slf4jApi", "julToSlf4j"]

[plugins]
asciiDoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciiDoctorGradle" }
gitVersioning = { id = "me.qoomon.git-versioning", version.ref = "gradleGitVersioning" }
gradleBuildInfo = { id = "com.opencastsoftware.gradle.buildinfo", version.ref = "gradleBuildInfo" }
gradleNode = { id = "com.github.node-gradle.node", version.ref = "gradleNode" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufGradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
